---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-build"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    generation: 1
    creationTimestamp: 
    labels:
      app: "${NAME}"
      template: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
      template: "${NAME}-build"
    annotations:
      description: Defines how to build the application
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_UPSTREAM_URL}"
        ref: "${GIT_UPSTREAM_REF}"
      contextDir: "${GIT_UPSTREAM_CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: "${S2I_BUILDER_IMAGE_NAMESPACE}"
          name: "${S2I_BUILDER_IMAGE}:${S2I_BUILDER_IMAGE_TAG}"
        env:
        - name: PIP_INDEX_URL
        - name: TAIGA_VERSION
          value: "${TAIGA_VERSION}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${IMAGESTREAM_TAG}"
    resources:
      limits:
parameters:
- name: NAME
  required: true
  value: taiga-back
- name: GIT_UPSTREAM_URL
  required: true
  value: https://github.com/springdo/openshift-taiga.git
- name: GIT_UPSTREAM_CONTEXT_DIR
  required: true
  value: https://github.com/springdo/openshift-taiga.git
- name: GIT_UPSTREAM_REF
  required: true
  value: "stable"
- name: IMAGESTREAM_TAG
  required: true
  value: latest
- name: S2I_BUILDER_IMAGE
  required: true
  value: python
- name: S2I_BUILDER_IMAGE_TAG
  required: true
  value: "3.6"
- name: S2I_BUILDER_IMAGE_NAMESPACE
  required: true
  value: openshift
- name: TAIGA_SETTINGS_VERSION
  required: true
  value: master
- name: TAIGA_VERSION
  required: true
  value: stable